# Generated by Django 5.2.7 on 2026-05-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(help_text='Temperatura en °C')),
                ('nivel_gas', models.IntegerField(help_text='Nivel de gas (0-1023)')),
                ('llama_detectada', models.BooleanField(default=False)),
                ('ventilador_extraccion', models.BooleanField(default=False)),
                ('ventilador_inyeccion_1', models.BooleanField(default=False)),
                ('ventilador_inyeccion_2', models.BooleanField(default=False)),
                ('estado_sistema', models.CharField(choices=[('NORMAL', 'Normal'), ('GAS_DETECTADO', 'Gas Detectado'), ('TEMPERATURA_ALTA', 'Temperatura Alta'), ('LLAMA_DETECTADA', 'Llama Detectada'), ('EMERGENCIA', 'Emergencia')], default='NORMAL', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Lecturas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
