# Generated by Django 5.2.7 on 2026-05-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='presion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Presión en hPa', max_digits=10),
        ),
    ]
