# Generated by Django 6.1 on 2026-08-14 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono_whatsapp', models.CharField(max_length=20)),
                ('telefono_llamada', models.CharField(blank=True, max_length=20)),
                ('recibe_llamada', models.BooleanField(default=False, help_text='Si esta activo, tambien se le llama por voz (no solo WhatsApp).')),
                ('activo', models.BooleanField(default=True)),
                ('cocina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliados', to='alertas.cocina')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ej: esp32-cocina-norte', max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('cocina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo', to='alertas.cocina')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAlarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='Activacion de boton fisico', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cocina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='alertas.cocina')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('llamada', 'Llamada')], max_length=10)),
                ('exitoso', models.BooleanField(default=False)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.afiliado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='alertas.eventoalarma')),
            ],
        ),
    ]
